### ISSUE TITLE
GCP Create Snapshot Across Projects

### ISSUE THREAD

**Issue by brondum** [vmware-tanzu/velero-plugin-for-gcp#15]
**Describe the problem/challenge you have**
Trying to create a snapshot across projects in GCP(gke).

**Describe the solution you'd like**
Would like to be able to specify which project the snapshot should be stored
e.g. creating a centralized backup project with both backups and snapshots.

**Environment:**

- Velero version (use `velero version`): 1.2.0
- Kubernetes version (use `kubectl version`): 1.14
- Cloud provider or hardware configuration: GKE

**Comment by skriss** [comment]
@brondum sorry for the delay here. I attempted to reproduce this, and as far as I can tell, things worked as expected, with the caveat that I don't actually have a second project set up to create a snapshot in, but I got to an error telling me that the "snapshot project" didn't exist when trying to create a snapshot.

My `cloud-credentials` secret contains the GCP service account JSON, including the following line:

```
...
"project_id": "<project where my disk is located>,
...
```

And my `VolumeSnapshotLocation` looks like the following:

```
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  labels:
    component: velero
  name: default
  namespace: velero
spec:
  config:
    project: snap-proj
  provider: gcp
```

The only error I end up getting with this setup is:

```
time="2020-01-17T16:15:24Z" level=error msg="Error backing up item" backup=velero/nginx-2 error="error taking snapshot of volume: rpc error: code = Unknown desc = googleapi: Error 404: Failed to find project snap-proj, notFound" group=v1 logSource="pkg/backup/resource_backupper.go:288" name=nginx-deployment-589cdf7bc4-7qtmc namespace=nginx-example resource=pods
```

Which indicates to me that it's correctly trying to create a snapshot in the `snap-proj` project.

Can you take a look and confirm that your config matches this? It sounds from your description like the `project_id` in your credentials file (in your `cloud-credentials` secret) contains the "snapshot project", rather than matching the project where the disk is.

**Comment by brondum** [comment]
@skriss I will try and set time aside for this monday, see if i can recreate the issue post the details here :)

**Comment by brondum** [comment]
@skriss Finally got to test the stuff, sorry for the delay here.

Okay so i double checked my credentials file.
it contains `the project_id` where both my cluster and my disks reside.

Then i added 
```yaml
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: default
  namespace: velero
spec:
  config:
    project: <THE PROJECT WHERE IT SHOULD END UP>
    snapshotLocation: europe-west4
  provider: velero.io/gcp
```

Outcome:
```
time="2020-01-22T13:42:21Z" level=info msg="1 errors encountered backup up item" backup=velero/testsnap group=v1 logSource="pkg/backup/resource_backupper.go:284" name=<SOMENAME> namespace= resource=pods
time="2020-01-22T13:42:21Z" level=error msg="Error backing up item" backup=velero/testsnap error="error taking snapshot of volume: rpc error: code = Unknown desc = googleapi: Error 404: The resource 'projects/<THE PROJECT WHERE IT SHOULD END UP>/zones/europe-west4-a/disks/<SOMEDISK>--pvc-c20bc2ef-1765-11ea-a35b-4201ac1f800a' was not found, notFound" group=v1 logSource="pkg/backup/resource_backupper.go:288" name=<POD_NAME> namespace= resource=pods
```

So from what i can se, it looks for the disk in the destination project instead of the source project ?
